// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4FAsetu6eUZJ4e9hDrCLRe5ZYc8vBSzk',
    appId: '1:789801348952:web:6cf554f1a14c2e0c06bf2d',
    messagingSenderId: '789801348952',
    projectId: 'facebook-1f364',
    authDomain: 'facebook-1f364.firebaseapp.com',
    storageBucket: 'facebook-1f364.appspot.com',
    measurementId: 'G-6NH49S9D4R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh1gJXZeGRkcHD17cY3AUCRju5VG6wIgA',
    appId: '1:789801348952:android:21a2d206c8e5469b06bf2d',
    messagingSenderId: '789801348952',
    projectId: 'facebook-1f364',
    storageBucket: 'facebook-1f364.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3WOXxxCfizEp8D2o2MtmQf8rzvhI94RE',
    appId: '1:789801348952:ios:0e77138ad250561606bf2d',
    messagingSenderId: '789801348952',
    projectId: 'facebook-1f364',
    storageBucket: 'facebook-1f364.appspot.com',
    iosBundleId: 'com.google.firebase.presents.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3WOXxxCfizEp8D2o2MtmQf8rzvhI94RE',
    appId: '1:789801348952:ios:b35bd88c6564f2cf06bf2d',
    messagingSenderId: '789801348952',
    projectId: 'facebook-1f364',
    storageBucket: 'facebook-1f364.appspot.com',
    iosBundleId: 'com.google.firebase.presents.demo.RunnerTests',
  );
}
